# Generated by Django 5.0.6 on 2024-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
